apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-pod
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: busybox:1.36
    command: ["/bin/sh","-c","sleep 300"]
    resources:
      limits:
        nvidia.com/gpu: 1
