apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-pod
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: nvidia/cuda:12.1-base
    command: ["/bin/sh","-c","nvidia-smi; sleep 300"]
    resources:
      limits:
        nvidia.com/gpu: 1
