apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    component: kube-scheduler
spec:
  hostNetwork: true
  restartPolicy: Always
  containers:
  - name: kube-scheduler
    # Use an official kube-scheduler image; we'll mount a host-built binary over
    # the image binary path so you can test your locally-built scheduler.
    image: k8s.gcr.io/kube-scheduler:v1.28.0
    command:
      - "/usr/local/bin/kube-scheduler"
      - "--config=/etc/kubernetes/scheduler.conf"
    volumeMounts:
      # mount the (host) built kube-scheduler binary over the image binary path
      - name: host-kube-scheduler-bin
        mountPath: /usr/local/bin/kube-scheduler
        subPath: kube-scheduler
      # expose device-plugin sockets so scheduler can call node-local /status
      - name: device-plugin-sock
        mountPath: /var/lib/kubelet/device-plugins
        readOnly: true
      # kube-scheduler config (host-provided)
      - name: scheduler-config
        mountPath: /etc/kubernetes/scheduler.conf
        subPath: scheduler.conf
        readOnly: true
    # run as root to allow host binary execution and unix-socket access
    securityContext:
      runAsUser: 0
  volumes:
    # Host binary: place your built binary on the control-plane host at
    # /opt/kube-scheduler/bin/kube-scheduler before starting this static pod.
    - name: host-kube-scheduler-bin
      hostPath:
        path: /opt/kube-scheduler/bin
        type: DirectoryOrCreate
    - name: device-plugin-sock
      hostPath:
        path: /var/lib/kubelet/device-plugins
        type: Directory
    - name: scheduler-config
      hostPath:
        path: /etc/kubernetes/scheduler.conf
        type: File

# Usage notes:
# 1) Copy your compiled kube-scheduler binary to the control-plane host under
#    `/opt/kube-scheduler/bin/kube-scheduler` (ensure executable).
# 2) Place your scheduler config at `/etc/kubernetes/scheduler.conf` on the
#    control-plane host (or adjust the hostPath in the manifest).
# 3) Save this file on the control-plane host (e.g. `/etc/kubernetes/manifests/kube-scheduler.yaml`).
#    The kubelet will start the static pod automatically.
# 4) Ensure the scheduler Pod can read `/var/lib/kubelet/device-plugins` (hostPath
#    is mounted read-only here) so it can contact node-local status sockets.
